openapi: 3.0.0
info:
  version: '1.0'
  title: "frigo"
  description: ""
  license:
     name: GPLv3
servers:
   - url: http://localhost:8000/api/v1

paths:
  /fridge:
    get:
      description: Get all the content of one fridge
      responses:
        '200':
          description: 'Collection of items'
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Item'
    post:
      description: 'Add an item to the fridge'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: "#/components/schemas/Item"
      responses:
        '200':
          description: "New item added"

  /fridge/{itemId}:
    get:
      description: Get the item with the specified itemId
      responses:
        '200':
          description: 'Searched item'
          content:
            application/json:
              schema:
                type: object
                $ref: '#/components/schemas/Item'
    patch:
      description: Set the item with the specified itemId as Opened
      responses:
        '200':
          description: 'Item updated'
          content:
            application/json:
              schema:
                type: object
                $ref: '#/components/schemas/Item'
    delete:
      description: Delete the item with the specified itemId
      responses:
        '200':
          description: 'Item updated'
          content:
            application/json:
              schema:
                type: object
                $ref: '#/components/schemas/Item'

  /fridge/{name}:
    get:
      parameters:
        - name: ownedBy
          in: path
          required: true
          schema:
            type: string
      description: Get all the items of one person
      responses:
        '200':
          description: "Collection of items of one person"
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Item'

components:
  schemas:
    Item:
      type: object
      required:
        - name
        - ownedBy
      properties:
        id:
          type: string
          format: uuid
          readOnly: true
        name:
          type: string
          maxLength: 30
        ownedBy:
          type: string
          maxLength: 20
        categoryId:
          type: integer
        amount:
          type: number
          format: float
        unit:
          type: string
          enum:
            - g
            - kg
            - ml
            - l
            - piece
        expDate: #Non nullable ma opzionale nel POST!! Se non presente prende la stima della Category
          type: string
          format: date
          readOnly: true
        openedAt:
          type: string
          format: date-time
          nullable: true
          readOnly: true
    Category:
      type: object
      required:
        - name
        - shelfLife
      properties:
        id:
          type: integer
          readOnly: true
        name:
          type: string
          maxLength: 20
        shelfLife:
          type: integer
          description: Shelf life in days
        openLife:
          type: integer
          nullable: true
          description: Shelf life in days after opening