{
 "title": "Metrics",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Number of things",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "number_of_things", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "New panel",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(http_requests_total{status!=\"200\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(status) (http_requests_total{status=\"200\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum by(method, status) (http_requests_total)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Backend logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{service_name=\"backend\"}"
    }
   ]
  },
  {
   "title": "databaseError per Minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum(count_over_time({service_name=\"backend\"} | json | event =~ `databaseError` [1m]))"
    }
   ]
  },
  {
   "title": "Events per  minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum(count_over_time({service_name=\"backend\"} | json | event=~`itemCreated|itemOpened|itemDeleted`[1m]))"
    }
   ]
  },
  {
   "title": "Percentili",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "histogram_quantile(\r\n  0.95,\r\n  sum by (le) (\r\n    rate(http_request_duration_seconds_bucket[5m])\r\n  )\r\n)*1000",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile(\r\n  0.99,\r\n  sum by (le) (\r\n    rate(http_request_duration_seconds_bucket[5m])\r\n  )\r\n)*1000",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile(\r\n  0.50,\r\n  sum by (le) (\r\n    rate(http_request_duration_seconds_bucket[5m])\r\n  )\r\n)*1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "New panel",
   "type": "__unconfigured-panel",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    { "legendFormat": "__auto" }
   ]
  }
 ]
}